FRONTEND_HTML = r"""
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title>Doctor Dev Panel</title>
  <style>
    :root{
      color-scheme:dark;
      --shell:#0b1220; --shell2:#111827; --bg:#f5f6f8; --surface:#ffffff; --surface2:#f8fafc;
      --text:#172033; --muted:#657083; --line:#dce3ee; --line2:#cbd5e1;
      --primary:#0a6ed1; --primary2:#085caf; --green:#107e3e; --red:#bb0000; --warn:#e9730c; --purple:#6a3fc5;
      --shadow:0 10px 32px rgba(15,23,42,.11); --radius:16px;
    }
    *{box-sizing:border-box}
    body{margin:0;font-family:Inter,"72",Segoe UI,Arial,sans-serif;background:var(--bg);color:var(--text)}
    .layout{display:grid;grid-template-columns:272px 1fr;min-height:100vh}
    aside{background:linear-gradient(180deg,var(--shell),var(--shell2));color:white;padding:18px 14px;position:sticky;top:0;height:100vh}
    .brand{display:flex;align-items:center;gap:10px;font-size:22px;font-weight:900;margin:8px 8px 22px;letter-spacing:-.04em}
    .brand-badge{width:38px;height:38px;border-radius:13px;background:#0a6ed1;display:grid;place-items:center;box-shadow:0 8px 20px rgba(10,110,209,.4)}
    .nav{display:grid;gap:6px}.nav a{color:#dbeafe;text-decoration:none;padding:11px 12px;border-radius:12px;display:flex;gap:10px;align-items:center;border:1px solid transparent}.nav a.active,.nav a:hover{background:rgba(255,255,255,.12);border-color:rgba(255,255,255,.14);color:white}
    .side-note{margin:22px 8px 0;padding:12px;border:1px solid rgba(255,255,255,.12);border-radius:14px;color:#bdd4ff;font-size:12px;line-height:1.7;background:rgba(255,255,255,.06)}
    main{min-width:0}.topbar{height:66px;background:rgba(255,255,255,.86);border-bottom:1px solid var(--line);display:flex;align-items:center;justify-content:space-between;padding:0 24px;position:sticky;top:0;z-index:5;backdrop-filter:blur(10px)}
    .page-title{font-weight:900;font-size:21px;letter-spacing:-.03em}.page-subtitle{font-size:13px;color:var(--muted);margin-top:3px}
    .content{padding:24px}.page{display:none}.page.active{display:block}.toolbar{display:flex;align-items:center;justify-content:space-between;gap:12px;margin-bottom:16px;flex-wrap:wrap}.toolbar-left,.toolbar-right,.actions{display:flex;gap:8px;flex-wrap:wrap;align-items:center}
    .card{background:var(--surface);border:1px solid var(--line);border-radius:var(--radius);box-shadow:var(--shadow);padding:18px}.soft-card{background:var(--surface2);border:1px solid var(--line);border-radius:14px;padding:14px}.grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(292px,1fr));gap:16px}.grid2{display:grid;grid-template-columns:1fr 1fr;gap:16px}.grid3{display:grid;grid-template-columns:repeat(3,1fr);gap:12px}.grid4{display:grid;grid-template-columns:repeat(4,1fr);gap:12px}.wide{grid-column:1/-1}
    h1,h2,h3{margin:0 0 10px;letter-spacing:-.025em}h2{font-size:20px}h3{font-size:15px}.muted{color:var(--muted);font-size:13px;line-height:1.65}.small{font-size:12px;color:#7b8798}.mono{font-family:ui-monospace,SFMono-Regular,Consolas,monospace}
    button{background:var(--primary);color:white;border:0;border-radius:10px;padding:10px 13px;font-weight:800;cursor:pointer;box-shadow:0 5px 14px rgba(10,110,209,.16)}button:hover{background:var(--primary2)}button.secondary{background:white;color:#233044;border:1px solid var(--line2);box-shadow:none}button.secondary:hover{background:#f8fafc}button.danger{background:var(--red)}button.warn{background:var(--warn)}button.purple{background:var(--purple)}button.ghost{background:transparent;color:var(--primary);box-shadow:none}button:disabled{opacity:.45;cursor:not-allowed}
    input,select,textarea{width:100%;border:1px solid var(--line2);border-radius:10px;padding:10px 11px;background:white;color:var(--text);outline:none}textarea{min-height:96px;resize:vertical;font-family:ui-monospace,Consolas,monospace}label{font-size:12px;color:#546174;font-weight:800;margin:0 0 6px;display:block}.field{min-width:0}.field-row{display:grid;gap:12px;margin-top:12px}.row2{grid-template-columns:1fr 1fr}.row3{grid-template-columns:repeat(3,1fr)}.row4{grid-template-columns:repeat(4,1fr)}
    .node-card{position:relative;cursor:pointer;transition:.16s transform,.16s box-shadow}.node-card:hover{transform:translateY(-2px);box-shadow:0 16px 38px rgba(15,23,42,.17)}.node-top{display:flex;justify-content:space-between;gap:10px}.node-check{position:absolute;top:14px;right:14px;width:18px;height:18px}.node-name{font-size:18px;font-weight:900;margin-right:32px}.endpoint{padding:8px 10px;background:#eef4ff;border:1px solid #d8e8ff;border-radius:10px;color:#174b7e;margin-top:12px}.pill{display:inline-flex;align-items:center;gap:5px;border-radius:999px;padding:4px 9px;font-size:12px;font-weight:800;background:#e8f2ff;color:#0a5ca8}.pill.online{background:#e5f5eb;color:#107e3e}.pill.offline{background:#ffebeb;color:#bb0000}.pill.unknown{background:#eef2f7;color:#56657a}.pill.run{background:#eaf4ff;color:#0a6ed1}.pill.warn{background:#fff4e5;color:#b85c00}
    .drawer{position:fixed;right:0;top:0;height:100vh;width:min(560px,96vw);background:white;border-left:1px solid var(--line);box-shadow:-20px 0 60px rgba(15,23,42,.22);z-index:10;transform:translateX(110%);transition:.2s transform;display:flex;flex-direction:column}.drawer.open{transform:translateX(0)}.drawer-head{padding:18px 20px;border-bottom:1px solid var(--line);display:flex;justify-content:space-between;align-items:center}.drawer-body{padding:20px;overflow:auto}.drawer-foot{border-top:1px solid var(--line);padding:14px 20px;display:flex;gap:8px;justify-content:flex-end}
    .builder{display:grid;grid-template-columns:1.08fr .92fr;gap:16px}.step{border-left:4px solid #91c8f6;background:#fbfdff;padding:14px;border-radius:12px;margin-bottom:12px}.list{display:grid;gap:10px}.item{padding:13px;border:1px solid var(--line);border-radius:13px;background:white}.tableish{display:grid;gap:8px}.pre{background:#0f172a;color:#dbeafe;border-radius:14px;padding:14px;overflow:auto;max-height:560px;white-space:pre-wrap;border:1px solid #1e293b}.toast{position:fixed;right:20px;bottom:20px;width:min(620px,calc(100vw - 40px));z-index:20}.toast .pre{max-height:280px}.quick-tiles{display:grid;grid-template-columns:repeat(auto-fit,minmax(230px,1fr));gap:16px}.tile{background:white;border:1px solid var(--line);border-radius:18px;box-shadow:var(--shadow);padding:18px}.tile-icon{width:42px;height:42px;border-radius:15px;display:grid;place-items:center;background:#e8f2ff;color:#0a6ed1;font-weight:900;margin-bottom:12px}.tile h3{font-size:17px}.sep{height:1px;background:var(--line);margin:14px 0}
    @media(max-width:980px){.layout{grid-template-columns:1fr}aside{position:relative;height:auto}.builder,.grid2,.row2,.row3,.row4{grid-template-columns:1fr}.topbar{position:relative;height:auto;padding:16px}.content{padding:16px}}
  </style>
</head>
<body>
<div class="layout">
  <aside>
    <div class="brand"><div class="brand-badge">D</div><div>Doctor Dev</div></div>
    <nav class="nav">
      <a href="#dashboard" data-page="dashboard" class="active">🏠 Dashboard</a>
      <a href="#nodes" data-page="nodes">🖥 Nodes</a>
      <a href="#cores" data-page="cores">🧩 Cores</a>
      <a href="#certificates" data-page="certificates">🔐 Certificates</a>
      <a href="#runtime" data-page="runtime">📊 Runtime</a>
      <a href="#versions" data-page="versions">🗂 Versions & Audit</a>
      <a href="#logs" data-page="logs">📜 Logs</a>
      <a href="#testlab" data-page="testlab">🧪 Local Test Lab</a>
      <a href="#output" data-page="output">📤 Output</a>
    </nav>
    <div class="side-note">Production-ready local panel layout: each work center has its own screen. Use scripts to reset, start agents, and launch the panel with generated admin credentials.</div>
  </aside>
  <main>
    <div class="topbar"><div><div id="pageTitle" class="page-title">Dashboard</div><div id="pageSubtitle" class="page-subtitle">Operate local nodes, cores, certificates and runtime tests.</div></div><div class="actions"><button onclick="loadAll()">Refresh</button><button class="secondary" onclick="seedLocal()">Seed Local Nodes</button></div></div>
    <div class="content">
      <section id="page-dashboard" class="page active">
        <div class="quick-tiles">
          <div class="tile"><div class="tile-icon">N</div><h3>Nodes</h3><p class="muted">Register local or remote node agents, edit connection settings, select multiple nodes and delete them safely.</p><button class="secondary" onclick="goPage('nodes')">Open Nodes</button></div>
          <div class="tile"><div class="tile-icon">C</div><h3>Core Builder</h3><p class="muted">Build tunnel inbounds, multiple listeners, route targets, local chains, remote groups and balancers.</p><button class="secondary" onclick="goPage('cores')">Open Cores</button></div>
          <div class="tile"><div class="tile-icon">TLS</div><h3>Certificates</h3><p class="muted">Manage certificate aliases independently from nodes, upload files, paste content or use panel/node paths.</p><button class="secondary" onclick="goPage('certificates')">Open Certificates</button></div>
          <div class="tile"><div class="tile-icon">T</div><h3>Local Test Lab</h3><p class="muted">Create test cores, apply them, run TCP/TLS checks and verify runtime metrics without a real server.</p><button class="secondary" onclick="goPage('testlab')">Open Test Lab</button></div>
        </div>
      </section>

      <section id="page-nodes" class="page">
        <div class="toolbar"><div class="toolbar-left"><button onclick="openNodeDrawer()">Add Node</button><button class="secondary" onclick="toggleSelectAllNodes()">Select All</button><button class="danger" onclick="deleteSelectedNodes()">Delete Selected</button><span id="selectedCount" class="pill unknown">0 selected</span></div><div class="toolbar-right"><input id="nodeSearch" placeholder="Search nodes..." oninput="renderNodes()" style="width:260px"/><button class="secondary" onclick="loadNodes()">Refresh Nodes</button></div></div>
        <div id="nodesGrid" class="grid"></div>
      </section>

      <section id="page-cores" class="page">
        <div class="builder">
          <div class="card">
            <div class="toolbar"><div><h2>Core Builder</h2><div class="muted">Build or edit a core. An inbound can listen on multiple IP/ports and route through static targets, local inbounds or remote node groups.</div></div><button class="secondary" onclick="clearBuilderForNew()">New Core</button></div>
            <div class="step"><h3>1. Core</h3><div class="field-row row3"><div class="field"><label>Node</label><select id="coreNode" onchange="renderRemoteNodeOptions()"></select></div><div class="field"><label>Existing Core</label><select id="editCore"></select></div><div class="field"><label>Core Name</label><input id="coreName" value="entry-core" /></div></div><div class="field-row"><div class="field"><label>Description</label><input id="coreDescription" value="Managed by Doctor Dev visual builder." /></div></div><div class="actions"><button class="secondary" onclick="loadCoreIntoBuilder()">Load Selected</button><button class="danger" onclick="deleteSelectedCore()">Delete Core</button></div></div>
            <div class="step"><h3>2. Inbound & Listeners</h3><div class="field-row row4"><div><label>Inbound Name</label><input id="inboundName" value="public-entry-inbound" /></div><div><label>Protocol</label><input id="inboundProtocol" value="tcp" /></div><div><label>Listen IP</label><input id="listenIp" value="127.0.0.1" /></div><div><label>Listen Ports CSV</label><input id="listenPorts" value="18080,18081" /></div></div><div class="field-row row2"><div><label>Max Users</label><input id="maxUsers" value="20" /></div><div><label>Max Active Connections</label><input id="maxActive" value="5" /></div></div></div>
            <div class="step"><h3>3. TLS</h3><div class="field-row row3"><div><label>TLS Mode</label><select id="tlsMode" onchange="renderTlsMode()"><option value="none">disabled</option><option value="stored">stored certificate alias</option><option value="file_on_panel">file path on panel</option><option value="file_on_node">file path on node</option><option value="pasted_content">paste content</option></select></div><div><label>Certificate Alias</label><select id="certSelect"></select></div><div><label>Domain</label><input id="tlsDomain" value="local.test" /></div></div><div id="tlsPathBox" class="field-row row2" style="display:none"><div><label>fullchain path</label><input id="tlsFullchainPath" value="certs/local.test/fullchain.pem" /></div><div><label>privkey path</label><input id="tlsPrivkeyPath" value="certs/local.test/privkey.pem" /></div></div><div id="tlsPasteBox" class="field-row row2" style="display:none"><div><label>fullchain content</label><textarea id="tlsFullchainContent"></textarea></div><div><label>privkey content</label><textarea id="tlsPrivkeyContent"></textarea></div></div><div class="actions"><button class="secondary" onclick="validateBuilderTls()">Validate TLS</button></div></div>
            <div class="step"><h3>4. Route & Targets</h3><div class="field-row row4"><div><label>Route Name</label><input id="routeName" value="entry-route" /></div><div><label>Balancer</label><select id="balancer"><option>round_robin</option><option>random</option><option>failover</option><option>weighted_round_robin</option></select></div><div><label>Target Mode</label><select id="targetMode" onchange="renderTargetMode()"><option value="local_chain">local inbound chain</option><option value="static">static IP/ports</option><option value="remote_group">remote node group</option></select></div><div><label>Weight / Priority</label><div style="display:grid;grid-template-columns:1fr 1fr;gap:8px"><input id="targetWeight" value="1"/><input id="targetPriority" value="10"/></div></div></div>
              <div id="staticTargetBox" class="soft-card" style="display:none;margin-top:12px"><h3>Static Target</h3><div class="field-row row2"><div><label>Host</label><input id="staticHost" value="127.0.0.1" /></div><div><label>Ports CSV</label><input id="staticPorts" value="3000,3001" /></div></div></div>
              <div id="localChainBox" class="soft-card" style="margin-top:12px"><h3>Local Inbound Chain</h3><div class="field-row row3"><div><label>Internal Inbound Name</label><input id="internalInboundName" value="internal-hop-inbound" /></div><div><label>Internal Listen IP</label><input id="internalListenIp" value="127.0.0.1" /></div><div><label>Internal Port</label><input id="internalPort" value="18100" /></div></div><div class="field-row row3"><div><label>Internal Balancer</label><select id="internalBalancer"><option>round_robin</option><option>weighted_round_robin</option><option>failover</option><option>random</option></select></div><div><label>Final Target Host</label><input id="internalTargetHost" value="127.0.0.1" /></div><div><label>Final Target Ports</label><input id="internalTargetPorts" value="3000,3001" /></div></div></div>
              <div id="remoteTargetBox" class="soft-card" style="display:none;margin-top:12px"><h3>Remote Node Group</h3><div class="field-row row3"><div><label>Remote Node</label><select id="remoteNode" onchange="renderRemoteCoreOptions()"></select></div><div><label>Remote Core</label><select id="remoteCore" onchange="renderRemoteInboundOptions()"></select></div><div><label>Remote Inbound</label><select id="remoteInbound"></select></div></div><div class="actions"><button class="secondary" onclick="refreshRemoteOptions()">Refresh Discovery</button></div></div>
            </div>
            <div class="actions"><button onclick="saveCoreFromBuilder()">Save Core</button><button class="secondary" onclick="previewPayload()">Preview Payload</button></div>
          </div>
          <div class="card"><h2>Cores</h2><div id="coresList" class="list"></div><div class="sep"></div><h2>Builder Preview</h2><pre id="builderPreview" class="pre">No payload yet.</pre><h2>Discovery</h2><pre id="discovery" class="pre">No discovery data yet.</pre></div>
        </div>
      </section>

      <section id="page-certificates" class="page">
        <div class="grid2"><div class="card"><h2>Certificate Manager</h2><p class="muted">Certificates are managed independently from nodes. Give each certificate a clear alias and use that alias inside cores.</p><div class="field-row row2"><div><label>Certificate Alias</label><input id="certName" value="local-test-cert" /></div><div><label>Domain</label><input id="certDomain" value="local.test" /></div></div><div class="field-row row2"><div><label>fullchain path</label><input id="certFullchainPath" value="certs/local.test/fullchain.pem" /></div><div><label>privkey path</label><input id="certPrivkeyPath" value="certs/local.test/privkey.pem" /></div></div><div class="actions"><button onclick="createPathCertificate()">Create Path Certificate</button><button class="secondary" onclick="validatePathCertificate()">Validate Paths</button><button class="secondary" onclick="loadCertificates()">Refresh</button></div><div class="sep"></div><h3>Upload from host</h3><div class="field-row row2"><div><label>fullchain.pem</label><input id="uploadFullchain" type="file" /></div><div><label>privkey.pem</label><input id="uploadPrivkey" type="file" /></div></div><div class="actions"><button class="purple" onclick="uploadCertificateFiles()">Upload Certificate Files</button></div></div><div class="card"><h2>Stored Certificate Aliases</h2><div id="certList" class="list"></div></div></div>
      </section>

      <section id="page-runtime" class="page"><div class="card"><h2>Runtime</h2><p class="muted">Fetch runtime metrics from all registered node agents or stop local runtime listeners.</p><div class="actions"><button onclick="fetchRuntimeAll()">Fetch Runtime From All Nodes</button><button class="warn" onclick="stopRuntimeAll()">Stop Runtime On All Nodes</button><button class="secondary" onclick="discoverAll()">Discover All Nodes</button></div></div></section>
      <section id="page-versions" class="page"><div class="grid2"><div class="card"><h2>Config Versions</h2><div id="versionsList" class="list"><p class="muted">Open a core from Cores and click Versions.</p></div></div><div class="card"><h2>Audit Log</h2><div class="actions"><button class="secondary" onclick="loadAuditLogs()">Refresh Audit Logs</button></div><pre id="auditBox" class="pre">No audit logs loaded.</pre></div></div></section>
      <section id="page-logs" class="page"><div class="card"><h2>Logs</h2><div class="actions"><button onclick="fetchLogsAll()">Fetch Logs From All Nodes</button></div><pre id="logsBox" class="pre">No logs loaded.</pre></div></section>
      <section id="page-testlab" class="page"><div class="grid2"><div class="card"><h2>Local Test Lab</h2><p class="muted">Run these flows after starting local agents. Tests create reusable cores and apply them to the agents.</p><div class="actions"><button class="secondary" onclick="seedLocal()">Seed Local Nodes</button><button class="secondary" onclick="createTlsTestCore()">Create TLS Test Core</button><button onclick="applyTlsTestCore()">Apply TLS Test Core</button><button class="secondary" onclick="createRemoteRoute()">Create Remote Route</button><button onclick="applyRemoteRoute()">Apply Remote Route</button></div><div class="sep"></div><div class="field-row row3"><div><label>Test Host</label><input id="testHost" value="127.0.0.1" /></div><div><label>Test Port</label><input id="testPort" value="18443" /></div><div><label>Payload</label><input id="testPayload" value="hello-doctor-dev" /></div></div><div class="actions"><button onclick="runTcpTest()">Run TCP Test</button><button class="purple" onclick="runTlsTest()">Run TLS Test</button></div></div><div class="card"><h2>Suggested Local Flow</h2><ol class="muted"><li>Seed Local Nodes.</li><li>Create TLS Test Core and Apply it.</li><li>Run TLS Test on 127.0.0.1:18443.</li><li>Create Remote Route and Apply it.</li><li>Run TCP Test on 127.0.0.1:18090.</li><li>Open Runtime and Logs.</li></ol></div></div></section>
      <section id="page-output" class="page"><div class="card"><h2>Output</h2><pre id="output" class="pre">Ready.</pre></div></section>
    </div>
  </main>
</div>

<div id="nodeDrawer" class="drawer"><div class="drawer-head"><div><h2 id="drawerTitle">Add Node</h2><div class="muted">Connection settings for the selected node agent.</div></div><button class="secondary" onclick="closeNodeDrawer()">Close</button></div><div class="drawer-body"><input id="nodeId" type="hidden"/><div class="field-row row2"><div><label>Node Name</label><input id="nodeName" value="local-node-c" /></div><div><label>Node Address</label><input id="nodeAddress" value="127.0.0.1" /></div></div><div class="field-row row3"><div><label>Node Port</label><input id="nodePort" value="62050" /></div><div><label>API Port</label><input id="nodeApiPort" value="9101" /></div><div><label>API Key</label><input id="nodeApiKey" value="local-dev-key-a" /></div></div><div class="field-row row2"><div><label>Keep Alive Value</label><input id="nodeKeepAlive" value="60" /></div><div><label>Keep Alive Unit</label><select id="nodeKeepAliveUnit"><option>seconds</option><option>minutes</option><option>hours</option></select></div></div><div class="field-row row2"><div><label>Default Timeout</label><input id="nodeDefaultTimeout" value="10" /></div><div><label>Internal Timeout</label><input id="nodeInternalTimeout" value="15" /></div></div><div class="field-row row2"><div><label>Data Limit GB</label><input id="nodeDataLimit" placeholder="optional" /></div><div><label>Proxy URL</label><input id="nodeProxyUrl" placeholder="optional" /></div></div><div class="field-row"><div><label>Certificate Content / Note</label><textarea id="nodeCertificate" placeholder="optional"></textarea></div></div></div><div class="drawer-foot"><button class="secondary" onclick="closeNodeDrawer()">Cancel</button><button onclick="saveNodeFromDrawer()">Save Node</button></div></div>
<div class="toast"><pre id="toastOutput" class="pre" style="display:none"></pre></div>

<script>
const $ = (id) => document.getElementById(id);
let nodes=[], cores=[], certs=[], discoveries={}, selectedCoreId='', selectedNodes=new Set();
const titles={dashboard:['Dashboard','Operate local nodes, cores, certificates and runtime tests.'],nodes:['Nodes','Card grid, edit drawer, multi-select and bulk delete.'],cores:['Cores','Visual core builder and core operations.'],certificates:['Certificates','Standalone certificate alias manager.'],runtime:['Runtime','Runtime metrics and listener control.'],versions:['Versions & Audit','Config version history, diff and rollback.'],logs:['Logs','Node log viewer.'],testlab:['Local Test Lab','End-to-end TCP/TLS test flows.'],output:['Output','Raw responses and diagnostics.']};
async function api(path, options={}){ const res=await fetch(path,{headers:{'Content-Type':'application/json',...(options.headers||{})},...options}); const text=await res.text(); let data; try{data=text?JSON.parse(text):{};}catch{data=text;} if(!res.ok) throw data; return data; }
function out(x){ const text=typeof x==='string'?x:JSON.stringify(x,null,2); $('output').textContent=text; $('toastOutput').style.display='block'; $('toastOutput').textContent=text; setTimeout(()=>$('toastOutput').style.display='none',5200); }
function goPage(page){ document.querySelectorAll('.page').forEach(p=>p.classList.remove('active')); const el=$('page-'+page); if(el) el.classList.add('active'); document.querySelectorAll('.nav a').forEach(a=>a.classList.toggle('active',a.dataset.page===page)); const t=titles[page]||titles.dashboard; $('pageTitle').textContent=t[0]; $('pageSubtitle').textContent=t[1]; location.hash=page; }
document.querySelectorAll('.nav a').forEach(a=>a.addEventListener('click',e=>{e.preventDefault();goPage(a.dataset.page)}));
window.addEventListener('hashchange',()=>goPage((location.hash||'#dashboard').slice(1))); if(location.hash) goPage(location.hash.slice(1));
function asInt(v,d=0){ const n=parseInt(v,10); return Number.isFinite(n)?n:d; } function csvPorts(v){ return String(v||'').split(',').map(x=>parseInt(x.trim(),10)).filter(n=>n>=1&&n<=65535); } function uid(p){ return `${p}_${Date.now().toString(16)}_${Math.random().toString(16).slice(2,6)}`; }
async function loadAll(){ await loadNodes(); await loadCores(); await loadCertificates(); renderBuilderSelects(); renderTargetMode(); renderTlsMode(); }
async function seedLocal(){ try{out(await api('/api/test-lab/seed-local',{method:'POST'})); await loadAll();}catch(e){out(e)} }
function nodeName(id){ const n=nodes.find(x=>x.id===id); return n?n.name:id; }
async function loadNodes(){ nodes=await api('/api/nodes'); renderNodes(); renderBuilderSelects(); }
function nodeMatches(n){ const q=($('nodeSearch')?.value||'').toLowerCase().trim(); return !q || [n.name,n.address,n.status,String(n.advanced?.api_port||'')].join(' ').toLowerCase().includes(q); }
function renderNodes(){ const items=nodes.filter(nodeMatches); $('nodesGrid').innerHTML=items.map(n=>`<div class="node-card card" onclick="openNodeDrawer('${n.id}')"><input class="node-check" type="checkbox" ${selectedNodes.has(n.id)?'checked':''} onclick="event.stopPropagation();toggleNodeSelection('${n.id}',this.checked)"><div class="node-top"><div><div class="node-name">${n.name}</div><span class="pill ${n.status||'unknown'}">${n.status||'unknown'}</span></div></div><div class="endpoint mono">${n.address}:${n.advanced?.api_port||n.node_port}</div><div class="muted" style="margin-top:10px">node port: ${n.node_port} · type: ${n.connection_type}<br>last seen: ${n.last_seen_at||'-'}</div><div class="actions" onclick="event.stopPropagation()"><button class="secondary" onclick="checkNode('${n.id}')">Check</button><button class="secondary" onclick="runtimeNode('${n.id}')">Runtime</button><button class="secondary" onclick="discoverNode('${n.id}')">Discovery</button></div></div>`).join('')||'<div class="card"><p class="muted">No nodes yet. Click Add Node or Seed Local Nodes.</p></div>'; updateSelectedCount(); }
function toggleNodeSelection(id,on){ on?selectedNodes.add(id):selectedNodes.delete(id); updateSelectedCount(); }
function updateSelectedCount(){ if($('selectedCount')) $('selectedCount').textContent=`${selectedNodes.size} selected`; }
function toggleSelectAllNodes(){ const visible=nodes.filter(nodeMatches); const all=visible.length&&visible.every(n=>selectedNodes.has(n.id)); visible.forEach(n=> all?selectedNodes.delete(n.id):selectedNodes.add(n.id)); renderNodes(); }
async function deleteSelectedNodes(){ try{ if(!selectedNodes.size) return out('Select at least one node.'); if(!confirm(`Delete ${selectedNodes.size} selected node(s)? Related cores and config versions will also be removed.`)) return; out(await api('/api/nodes/bulk-delete',{method:'POST',body:JSON.stringify({node_ids:[...selectedNodes]})})); selectedNodes.clear(); await loadAll(); }catch(e){out(e)} }
function openNodeDrawer(id=''){ const n=id?nodes.find(x=>x.id===id):null; $('drawerTitle').textContent=n?'Edit Node':'Add Node'; $('nodeId').value=n?.id||''; $('nodeName').value=n?.name||'local-node-c'; $('nodeAddress').value=n?.address||'127.0.0.1'; $('nodePort').value=n?.node_port||62050; $('nodeApiPort').value=n?.advanced?.api_port||9101; $('nodeApiKey').value=n?.api_key||'local-dev-key-a'; $('nodeKeepAlive').value=n?.advanced?.keep_alive?.value||60; $('nodeKeepAliveUnit').value=n?.advanced?.keep_alive?.unit||'seconds'; $('nodeDefaultTimeout').value=n?.advanced?.default_timeout||10; $('nodeInternalTimeout').value=n?.advanced?.internal_timeout||15; $('nodeDataLimit').value=n?.advanced?.data_limit_gb||''; $('nodeProxyUrl').value=n?.advanced?.proxy_url||''; $('nodeCertificate').value=n?.certificate||''; $('nodeDrawer').classList.add('open'); }
function closeNodeDrawer(){ $('nodeDrawer').classList.remove('open'); }
async function saveNodeFromDrawer(){ try{ const id=$('nodeId').value; const body={name:$('nodeName').value,address:$('nodeAddress').value,node_port:asInt($('nodePort').value,62050),api_key:$('nodeApiKey').value,connection_type:'grpc',advanced:{api_port:asInt($('nodeApiPort').value,9101),keep_alive:{value:asInt($('nodeKeepAlive').value,60),unit:$('nodeKeepAliveUnit').value},data_limit_gb:$('nodeDataLimit').value?asInt($('nodeDataLimit').value):null,default_timeout:asInt($('nodeDefaultTimeout').value,10),internal_timeout:asInt($('nodeInternalTimeout').value,15),proxy_url:$('nodeProxyUrl').value||null},certificate:$('nodeCertificate').value||null}; const result=await api(id?`/api/nodes/${id}`:'/api/nodes',{method:id?'PUT':'POST',body:JSON.stringify(body)}); out(result); closeNodeDrawer(); await loadAll(); }catch(e){out(e)} }
async function checkNode(id){ try{out(await api(`/api/nodes/${id}/check-status`,{method:'POST'})); await loadNodes();}catch(e){out(e)} } async function runtimeNode(id){ try{out(await api(`/api/nodes/${id}/runtime`));}catch(e){out(e)} } async function discoverNode(id){ try{discoveries[id]=await api(`/api/nodes/${id}/discovery`); $('discovery').textContent=JSON.stringify(discoveries[id],null,2); renderRemoteNodeOptions(); goPage('cores');}catch(e){out(e)} }
async function loadCertificates(){ try{certs=await api('/api/certificates'); $('certList').innerHTML=certs.map(c=>`<div class="item"><h3>${c.name} <span class="pill">${c.mode}</span></h3><div class="muted">alias: <b>${c.name}</b><br>domain: ${c.domain}<br>fullchain: ${c.fullchain_path||'inline'}<br>privkey: ${c.privkey_path||'inline'}</div><div class="actions"><button class="secondary" onclick="useCertInBuilder('${c.id}')">Use in Core Builder</button><button class="danger" onclick="deleteCertificate('${c.id}')">Delete</button></div></div>`).join('')||'<p class="muted">No certificate aliases yet.</p>'; if($('certSelect')) $('certSelect').innerHTML=certs.map(c=>`<option value="${c.id}">${c.name} / ${c.domain}</option>`).join(''); }catch(e){out(e)} }
function useCertInBuilder(id){ $('tlsMode').value='stored'; $('certSelect').value=id; const c=certs.find(x=>x.id===id); if(c) $('tlsDomain').value=c.domain||'local.test'; renderTlsMode(); goPage('cores'); }
async function deleteCertificate(id){ try{out(await api(`/api/certificates/${id}`,{method:'DELETE'})); await loadCertificates();}catch(e){out(e)} } async function createPathCertificate(){ try{const body={name:$('certName').value,domain:$('certDomain').value,mode:'file_on_panel',fullchain_path:$('certFullchainPath').value,privkey_path:$('certPrivkeyPath').value,location:'panel'}; out(await api('/api/certificates',{method:'POST',body:JSON.stringify(body)})); await loadCertificates();}catch(e){out(e)} }
async function validatePathCertificate(){ try{const body={mode:'file_on_panel',domain:$('certDomain').value,fullchain_path:$('certFullchainPath').value,privkey_path:$('certPrivkeyPath').value}; out(await api('/api/certificates/validate',{method:'POST',body:JSON.stringify(body)}));}catch(e){out(e)} } async function uploadCertificateFiles(){ try{const fd=new FormData(); fd.append('name',$('certName').value); fd.append('domain',$('certDomain').value); if(!$('uploadFullchain').files[0]||!$('uploadPrivkey').files[0]) return out('Choose both fullchain.pem and privkey.pem'); fd.append('fullchain',$('uploadFullchain').files[0]); fd.append('privkey',$('uploadPrivkey').files[0]); const res=await fetch('/api/certificates/upload',{method:'POST',body:fd}); const data=await res.json(); if(!res.ok) throw data; out(data); await loadCertificates();}catch(e){out(e)} }
async function getStoredCertRef(){ const id=$('certSelect').value; if(!id) return null; return await api(`/api/certificates/${id}/ref`); } function renderTlsMode(){ const mode=$('tlsMode')?.value||'none'; if(!$('tlsPathBox'))return; $('tlsPathBox').style.display=(mode==='file_on_panel'||mode==='file_on_node')?'grid':'none'; $('tlsPasteBox').style.display=mode==='pasted_content'?'grid':'none'; }
async function buildTlsRef(){ const mode=$('tlsMode').value; if(mode==='none') return {enabled:false,mode:'none'}; if(mode==='stored'){ const ref=await getStoredCertRef(); return ref||{enabled:false,mode:'none'}; } if(mode==='pasted_content') return {enabled:true,mode:'pasted_content',domain:$('tlsDomain').value,fullchain_content:$('tlsFullchainContent').value,privkey_content:$('tlsPrivkeyContent').value}; return {enabled:true,mode,domain:$('tlsDomain').value,fullchain_path:$('tlsFullchainPath').value,privkey_path:$('tlsPrivkeyPath').value}; } async function validateBuilderTls(){ try{const tls=await buildTlsRef(); if(!tls.enabled) return out({ok:true,message:'TLS disabled'}); out(await api('/api/certificates/validate',{method:'POST',body:JSON.stringify(tls)}));}catch(e){out(e)} }
async function loadCores(){ cores=await api('/api/cores'); $('coresList').innerHTML=cores.map(c=>`<div class="item"><h3>${c.name} <span class="pill run">${c.status}</span></h3><div class="muted">node: ${nodeName(c.node_id)}<br>inbounds: ${c.inbounds.length} · routes: ${c.routes.length}</div><div class="actions"><button class="secondary" onclick="selectCoreForEdit('${c.id}')">Edit</button><button class="secondary" onclick="dryRun('${c.id}')">Dry Run</button><button onclick="applyCore('${c.id}')">Apply</button><button class="secondary" onclick="showConfig('${c.id}')">Config</button><button class="secondary" onclick="loadVersions('${c.id}')">Versions</button><button class="purple" onclick="diffCore('${c.id}')">Diff</button></div></div>`).join('')||'<p class="muted">No cores yet.</p>'; renderBuilderSelects(); }
function renderBuilderSelects(){ if(!$('coreNode'))return; $('coreNode').innerHTML=nodes.map(n=>`<option value="${n.id}">${n.name}</option>`).join(''); $('editCore').innerHTML='<option value="">Create new core</option>'+cores.map(c=>`<option value="${c.id}">${c.name} / ${nodeName(c.node_id)}</option>`).join(''); $('certSelect').innerHTML=certs.map(c=>`<option value="${c.id}">${c.name} / ${c.domain}</option>`).join(''); renderRemoteNodeOptions(); }
function renderTargetMode(){ if(!$('targetMode'))return; const mode=$('targetMode').value; $('staticTargetBox').style.display=mode==='static'?'block':'none'; $('localChainBox').style.display=mode==='local_chain'?'block':'none'; $('remoteTargetBox').style.display=mode==='remote_group'?'block':'none'; }
function renderRemoteNodeOptions(){ if(!$('remoteNode'))return; const current=$('coreNode')?.value; $('remoteNode').innerHTML=nodes.filter(n=>n.id!==current).map(n=>`<option value="${n.id}">${n.name}</option>`).join(''); renderRemoteCoreOptions(); } function renderRemoteCoreOptions(){ const nodeId=$('remoteNode')?.value; const d=discoveries[nodeId]; const nodeCores=d?d.cores:cores.filter(c=>c.node_id===nodeId); $('remoteCore').innerHTML=nodeCores.map(c=>`<option value="${c.id}">${c.name}</option>`).join(''); renderRemoteInboundOptions(); } function renderRemoteInboundOptions(){ const nodeId=$('remoteNode')?.value, coreId=$('remoteCore')?.value; const d=discoveries[nodeId]; let inbounds=[]; if(d){ const c=(d.cores||[]).find(x=>x.id===coreId); inbounds=c?c.inbounds:[]; } else { const c=cores.find(x=>x.id===coreId); inbounds=c?c.inbounds:[]; } $('remoteInbound').innerHTML=inbounds.map(i=>`<option value="${i.id}">${i.name}</option>`).join(''); }
async function refreshRemoteOptions(){ try{ for(const n of nodes) discoveries[n.id]=await api(`/api/nodes/${n.id}/discovery`); $('discovery').textContent=JSON.stringify(Object.values(discoveries),null,2); renderRemoteNodeOptions(); }catch(e){out(e)} }
async function buildPayload(){ const mode=$('targetMode').value; const publicRouteId=uid('route'), publicInboundId=uid('inbound'); const publicListeners=csvPorts($('listenPorts').value).map(p=>({listen_ip:$('listenIp').value,listen_port:p,port_mode:'fixed',enabled:true})); const publicTls=await buildTlsRef(); const publicInbound={id:publicInboundId,name:$('inboundName').value,type:'tunnel',protocol:$('inboundProtocol').value||'tcp',enabled:true,listeners:publicListeners,tls:publicTls,limits:{},route_id:publicRouteId}; const mu=asInt($('maxUsers').value), ma=asInt($('maxActive').value); if(mu>0) publicInbound.limits.max_users=mu; if(ma>0) publicInbound.limits.max_active_connections=ma; const publicRoute={id:publicRouteId,name:$('routeName').value,balancer:$('balancer').value,fallback_behavior:'error',enabled:true,targets:[]}; const inbounds=[publicInbound], routes=[publicRoute]; if(mode==='static'){ publicRoute.targets.push({type:'static',enabled:true,priority:asInt($('targetPriority').value,10),weight:asInt($('targetWeight').value,1),host:$('staticHost').value,ports:csvPorts($('staticPorts').value)}); } else if(mode==='remote_group'){ publicRoute.targets.push({type:'remote_group',enabled:true,priority:asInt($('targetPriority').value,10),weight:asInt($('targetWeight').value,1),remote_node_id:$('remoteNode').value,remote_core_id:$('remoteCore').value||null,remote_inbound_id:$('remoteInbound').value||null}); } else { const internalRouteId=uid('route'), internalInboundId=uid('inbound'); const internalInbound={id:internalInboundId,name:$('internalInboundName').value,type:'tunnel',protocol:'tcp',enabled:true,listeners:[{listen_ip:$('internalListenIp').value,listen_port:asInt($('internalPort').value,18100),port_mode:'fixed',enabled:true}],tls:{enabled:false,mode:'none'},limits:{max_users:100,max_active_connections:50},route_id:internalRouteId}; const internalRoute={id:internalRouteId,name:'internal-to-final-targets',balancer:$('internalBalancer').value,fallback_behavior:'error',enabled:true,targets:[{type:'static',enabled:true,priority:10,weight:1,host:$('internalTargetHost').value,ports:csvPorts($('internalTargetPorts').value)}]}; publicRoute.targets.push({type:'local_inbound',enabled:true,priority:asInt($('targetPriority').value,10),weight:asInt($('targetWeight').value,1),local_inbound_id:internalInboundId}); inbounds.push(internalInbound); routes.push(internalRoute); } return {node_id:$('coreNode').value,name:$('coreName').value,enabled:true,description:$('coreDescription').value,inbounds,routes,advanced_config:{created_by:'doctor_dev_visual_builder',target_mode:mode}}; }
async function previewPayload(){ const body=await buildPayload(); $('builderPreview').textContent=JSON.stringify(body,null,2); out({ok:true,message:'payload generated',body}); } async function saveCoreFromBuilder(){ try{const body=await buildPayload(); const coreId=$('editCore').value||selectedCoreId; const result=await api(coreId?`/api/cores/${coreId}`:'/api/cores',{method:coreId?'PUT':'POST',body:JSON.stringify(body)}); selectedCoreId=result.id; $('builderPreview').textContent=JSON.stringify(result,null,2); out(result); await loadCores(); $('editCore').value=selectedCoreId;}catch(e){out(e)} }
async function selectCoreForEdit(id){ $('editCore').value=id; await loadCoreIntoBuilder(); goPage('cores'); } async function loadCoreIntoBuilder(){ try{ const id=$('editCore').value; if(!id)return out('Choose an existing core first.'); const c=await api(`/api/cores/${id}`); selectedCoreId=id; $('coreNode').value=c.node_id; $('coreName').value=c.name; $('coreDescription').value=c.description||''; const inbound=c.inbounds[0], route=c.routes.find(r=>r.id===inbound?.route_id)||c.routes[0]; if(inbound){ $('inboundName').value=inbound.name; $('inboundProtocol').value=inbound.protocol; $('listenIp').value=(inbound.listeners[0]||{}).listen_ip||'127.0.0.1'; $('listenPorts').value=inbound.listeners.map(l=>l.listen_port).filter(Boolean).join(','); $('maxUsers').value=inbound.limits.max_users||''; $('maxActive').value=inbound.limits.max_active_connections||''; $('tlsMode').value=(inbound.tls&&inbound.tls.enabled)?(inbound.tls.id?'stored':inbound.tls.mode):'none'; if(inbound.tls){$('tlsDomain').value=inbound.tls.domain||'local.test'; $('tlsFullchainPath').value=inbound.tls.fullchain_path||''; $('tlsPrivkeyPath').value=inbound.tls.privkey_path||''; if(inbound.tls.id)$('certSelect').value=inbound.tls.id;} } if(route){ $('routeName').value=route.name; $('balancer').value=route.balancer; const t=route.targets[0]; if(t){$('targetWeight').value=t.weight||1; $('targetPriority').value=t.priority||10; if(t.type==='static'){$('targetMode').value='static'; $('staticHost').value=t.host||'127.0.0.1'; $('staticPorts').value=(t.ports||[]).join(',');} else if(t.type==='remote_group'){$('targetMode').value='remote_group'; await refreshRemoteOptions(); $('remoteNode').value=t.remote_node_id||''; renderRemoteCoreOptions(); $('remoteCore').value=t.remote_core_id||''; renderRemoteInboundOptions(); $('remoteInbound').value=t.remote_inbound_id||'';} else {$('targetMode').value='local_chain'; const ii=c.inbounds.find(i=>i.id===t.local_inbound_id); if(ii){$('internalInboundName').value=ii.name; $('internalListenIp').value=(ii.listeners[0]||{}).listen_ip||'127.0.0.1'; $('internalPort').value=(ii.listeners[0]||{}).listen_port||18100; const ir=c.routes.find(r=>r.id===ii.route_id); if(ir){$('internalBalancer').value=ir.balancer; const st=ir.targets[0]||{}; $('internalTargetHost').value=st.host||'127.0.0.1'; $('internalTargetPorts').value=(st.ports||[]).join(',');}}} } } renderTargetMode(); renderTlsMode(); $('builderPreview').textContent=JSON.stringify(c,null,2); out({ok:true,loaded:c.name}); }catch(e){out(e)} }
function clearBuilderForNew(){ selectedCoreId=''; $('editCore').value=''; $('coreName').value='entry-core'; $('builderPreview').textContent='No payload yet.'; }
async function deleteSelectedCore(){ try{const id=$('editCore').value||selectedCoreId; if(!id)return out('Choose a core first.'); if(!confirm('Delete selected core?'))return; out(await api(`/api/cores/${id}`,{method:'DELETE'})); selectedCoreId=''; await loadCores();}catch(e){out(e)} }
async function dryRun(id){ try{out(await api(`/api/cores/${id}/dry-run`,{method:'POST'}));}catch(e){out(e)} } async function applyCore(id){ try{out(await api(`/api/cores/${id}/apply`,{method:'POST'})); await loadCores();}catch(e){out(e)} } async function showConfig(id){ try{out(await api(`/api/cores/${id}/config`)); goPage('output');}catch(e){out(e)} }
async function loadVersions(id){ try{const data=await api(`/api/cores/${id}/versions`); $('versionsList').innerHTML=data.versions.map(v=>`<div class="item"><h3>v${v.version_no} <span class="pill">${v.kind}</span> <span class="pill run">${v.status}</span></h3><div class="muted">${v.created_at}<br>core: ${v.core_name}</div><div class="actions"><button class="secondary" onclick="showVersion('${v.id}')">View</button><button class="purple" onclick="diffVersion('${data.core_id}','${v.id}')">Diff to Current</button><button class="warn" onclick="rollbackVersion('${data.core_id}','${v.id}')">Rollback + Apply</button></div></div>`).join('')||'<p class="muted">No versions yet. Run Dry Run or Apply first.</p>'; out(data); goPage('versions');}catch(e){out(e)} }
async function showVersion(versionId){ try{out(await api(`/api/config-versions/${versionId}`)); goPage('output');}catch(e){out(e)} } async function diffCore(id){ try{const data=await api(`/api/cores/${id}/diff`); out(data.diff?data.diff.join('\n'):data); goPage('output');}catch(e){out(e)} } async function diffVersion(coreId,versionId){ try{const data=await api(`/api/cores/${coreId}/diff?from_version_id=${versionId}`); out(data.diff?data.diff.join('\n'):data);}catch(e){out(e)} } async function rollbackVersion(coreId,versionId){ try{if(!confirm('Rollback this core to the selected version and apply it?'))return; out(await api(`/api/cores/${coreId}/rollback/${versionId}?apply_after_restore=true`,{method:'POST'})); await loadCores(); await loadVersions(coreId); await loadAuditLogs();}catch(e){out(e)} } async function loadAuditLogs(){ try{const data=await api('/api/audit-logs?limit=200'); $('auditBox').textContent=JSON.stringify(data.logs,null,2); out(data);}catch(e){out(e)} }
async function fetchRuntimeAll(){ try{if(!nodes.length) await loadNodes(); const all=[]; for(const n of nodes) all.push({node:n.name,runtime:await api(`/api/nodes/${n.id}/runtime`)}); out(all);}catch(e){out(e)} } async function stopRuntimeAll(){ try{if(!nodes.length) await loadNodes(); const all=[]; for(const n of nodes) all.push({node:n.name,result:await api(`/api/nodes/${n.id}/stop-runtime`,{method:'POST'})}); out(all);}catch(e){out(e)} } async function discoverAll(){ try{if(!nodes.length) await loadNodes(); const all=[]; for(const n of nodes){discoveries[n.id]=await api(`/api/nodes/${n.id}/discovery`); all.push(discoveries[n.id]);} $('discovery').textContent=JSON.stringify(all,null,2); out(all);}catch(e){out(e)} }
async function fetchLogsAll(){ try{if(!nodes.length) await loadNodes(); let text=''; for(const n of nodes){const data=await api(`/api/nodes/${n.id}/logs?limit=400`); text+=`\n===== ${n.name} =====\n`+(data.lines||[]).join('\n')+'\n';} $('logsBox').textContent=text; goPage('logs');}catch(e){out(e)} }
async function runTcpTest(){ try{const host=$('testHost').value, port=$('testPort').value, payload=encodeURIComponent($('testPayload').value); out(await api(`/api/test/tcp?host=${host}&port=${port}&payload=${payload}`,{method:'POST'}));}catch(e){out(e)} } async function runTlsTest(){ try{const host=$('testHost').value, port=$('testPort').value||18443, payload=encodeURIComponent($('testPayload').value||'hello-doctor-dev-tls'); out(await api(`/api/test/tls-tcp?host=${host}&port=${port}&payload=${payload}&verify=false`,{method:'POST'}));}catch(e){out(e)} }
async function createTlsTestCore(){ try{const data=await api('/api/test-lab/create-tls-core',{method:'POST'}); out(data); await loadCores(); if(data.test){$('testHost').value=data.test.host; $('testPort').value=data.test.port; $('testPayload').value=data.test.payload;}}catch(e){out(e)} } async function applyTlsTestCore(){ try{const data=await api('/api/test-lab/apply-tls-core',{method:'POST'}); out(data); await loadCores(); if(data.test){$('testHost').value=data.test.host; $('testPort').value=data.test.port; $('testPayload').value=data.test.payload;}}catch(e){out(e)} } async function createRemoteRoute(){ try{const data=await api('/api/test-lab/create-remote-route',{method:'POST'}); out(data); await loadCores(); if(data.test){$('testHost').value=data.test.host; $('testPort').value=data.test.port; $('testPayload').value=data.test.payload;}}catch(e){out(e)} } async function applyRemoteRoute(){ try{const data=await api('/api/test-lab/apply-remote-route',{method:'POST'}); out(data); await loadCores(); $('testHost').value='127.0.0.1'; $('testPort').value='18090'; $('testPayload').value='hello-remote-route';}catch(e){out(e)} }
loadAll().catch(out);
</script>
</body>
</html>
"""
